
executor: KubernetesExecutor

airflowVersion: "2.11.2"

defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.11.2-python3.11"

webserver:
  service:
    type: ClusterIP
ingress:
  web:
    enabled: true
    ingressClassName: nginx
    hosts:
      - name: airflow.cyan.com
        tls:
          enabled: false

env:
  - name: DATAWORKS_BASE_URL
    value: "http://cyan-dataworks-svc.pre.svc.cluster.local:8080"
  - name: DATAWORKS_DAG_DEFINITION_ENDPOINT
    value: "/rpc/dataworks/airflow/workflow-dag-definitions"
  - name: AIRFLOW_CONN_DATAWORKS_HTTP
    value: "http://cyan-dataworks-svc.pre.svc.cluster.local:8080"

extraEnv: |
  - name: DATAWORKS_TOKEN
    valueFrom:
      secretKeyRef:
        name: dataworks-airflow-token
        key: token
  - name: AIRFLOW_CONN_AIRFLOW_LOGS_S3
    valueFrom:
      secretKeyRef:
        name: airflow-rustfs-logs
        key: connection

extraPipPackages:
  - apache-airflow-providers-http
  - apache-airflow-providers-amazon
  - requests

volumes:
  - name: dataworks-airflow-dags
    configMap:
      name: dataworks-airflow-dags

volumeMounts:
  - name: dataworks-airflow-dags
    mountPath: /opt/airflow/dags/dataworks_dynamic_dag_factory.py
    subPath: dataworks_dynamic_dag_factory.py
    readOnly: true

postgresql:
  primary:
    persistence:
      enabled: true
      storageClass: local-path
      size: 20Gi

triggerer:
  persistence:
    enabled: false

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: false

config:
  core:
    load_examples: "False"
    dags_are_paused_at_creation: "False"
  api:
    auth_backends: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
  logging:
    remote_logging: "True"
    remote_base_log_folder: "s3://airflow-logs/dataworks-airflow"
    remote_log_conn_id: "airflow_logs_s3"
    encrypt_s3_logs: "False"
