spring:
  profiles:
    active: dev
  application:
    name: cyan-dataworks
  cloud:
    openfeign:
      okhttp:
        enabled: true
  main:
    web-application-type: servlet
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
flink:
  rest:
    url: http://10.0.0.2:18083
    preview-poll-times: 10
    preview-poll-interval-ms: 500
    preview-max-result-pages: 20
    preview-max-result-rows: 100
  iceberg-catalog:
    enabled: true
    name: iceberg
    type: iceberg
    catalog-type: rest
    uri: http://gravitino-iceberg-rest-server.gravitino.svc.cluster.local:9001/iceberg
    s3-endpoint: http://10.0.0.2:9000
    s3-access-key-id: rustfsadmin
    s3-secret-access-key: rustfsadmin
    s3-path-style-access: true
  operator:
    enabled: true
    namespace: dataworks
    image: harbor.cyan.com/cyan/dataworks-flink-sql:2.0.1
    jar-uri: local:///opt/flink/lib/flink-sql-runner.jar
    entry-class: com.cyan.dataworks.flink.SqlRunner
    parallelism: 1
airflow:
  enabled: ${AIRFLOW_ENABLED:true}
  base-url: ${AIRFLOW_BASE_URL:http://dataworks-airflow-webserver.airflow.svc.cluster.local:8080}
  username: ${AIRFLOW_USERNAME:admin}
  password: ${AIRFLOW_PASSWORD:admin}
  remote-log:
    endpoint: http://10.0.0.2:9000
    access-key: rustfsadmin
    secret-key: rustfsadmin
    bucket: airflow-logs
    base-prefix: dataworks-airflow
dataworks:
  spark-operator:
    namespace: spark
    api-version: sparkoperator.k8s.io/v1beta2
    image: harbor.cyan.com/cyan/dataworks-spark-sql:4.0.2
    image-pull-policy: Always
    image-pull-secret: harbor-secret
    type: Java
    spark-version: 4.0.2
    main-application-file: local:///opt/spark/app/dataworks-spark-runner.jar
    main-class: com.cyan.dataworks.spark.SqlRunner
    service-account: spark-operator-spark
    driver-cores: 1
    driver-memory: 1g
    driver-core-limit: 1200m
    executor-instances: 1
    executor-cores: 1
    executor-memory: 2g
    executor-core-limit: 1200m
    ttl-seconds-after-finished: 300
    sql-mount-path: /opt/spark/work-dir/dataworks
    time-zone: Asia/Shanghai
    iceberg-rest-uri: http://gravitino-iceberg-rest-server.gravitino.svc.cluster.local:9001/iceberg
    rustfs-endpoint: http://10.0.0.2:9000
    rustfs-access-key: rustfsadmin
    rustfs-secret-key: rustfsadmin
